language: android

branches:
  only:
    - develop
    - /^v\.\d\.\d\.\d$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.10

jdk:
  - oraclejdk8

android:
  components:
   - tools
   - build-tools-24.0.0
   - android-24
   - extra-android-m2repository
  licenses:
   - android-sdk-license-.+

script: ./gradlew assemble

deploy:
  provider: script
  script: ./gradlew bintrayUpload -PbintrayUser=alorma -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  on:
   tags: true
